### ISSUE TITLE
Invalid function current_time()

### ISSUE THREAD

**Issue by mudrd8mz** [VdoCipher/moodle-filter_vdocipher#1]
The function eval_date() attempts to call another function current_time(). But there is no such function in Moodle core API. Maybe you copied over some Wordpress code? (as they have such function).

Also, the whole hack with conditionally creating the function `eval_date()` smells. Why not to use properly defined (and correctly named) function?

**Comment by vibhavsinha** [comment]
Thanks so much for your review during the early days of this plugin. I had corrected this and another issue based on your review but missed updating this issue. Closing it now.
